#!/bin/bash
MEMORY=/tmp/last_opened_tutorial.txt
RENDERED=/tmp/bootkon.md

FILE=$1

if [[ -z "${FILE}" ]]; then
    if [[ -f "${MEMORY}" ]]; then
        FILE=$(cat $MEMORY)
        echo "No tutorial specified. Reloading last opened file ${FILE}"
    fi
fi

echo $FILE > /tmp/last_opened_tutorial.txt

jinja2 $FILE -o $RENDERED
cloudshell launch-tutorial -d $RENDERED