#!/bin/bash
# This script initializes the Data & AI Bootkon environment in Cloud Shell.
# It clones the Bootkon repository (or uses an existing one), sets up necessary
# environment variables, installs required packages, renders the tutorial markdown file,
# and finally opens the tutorial in Cloud Shell. It also adds helpful aliases and
# configurations to the .bashrc file for easier future access and customization.
#
# Author: Fabian Hirschmann
#
# Usage:
#   From GitHub (replace <username/repo>):
#     BK_REPO=<username/repo>; . <(wget -qO- https://raw.githubusercontent.com/<username/repo>/main/.scripts/bk)
#   Locally:
#     BK_REPO=<username/repo> . bk
#   Defaults, repo as argument:
#     . bk <username/repo>
#
#   Skip workspace opening (add to ~/.bashrc above bk):
#     export BK_NO_WORKSPACE_OPEN=1
#
# Environment variables:
#   BK_REPO: GitHub repository (<username/repo>). Defaults to fhirschmann/bootkon.
#   BK_TUTORIAL: Path to tutorial markdown (relative to repo root). Defaults to .TUTORIAL.md.
#   BK_NO_WORKSPACE_OPEN: Prevents workspace auto-opening.

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

err() {
  echo -e "${RED}Error: $1${NC}" >&2
}

echo -e "${YELLOW}Running bootkon init script $(readlink -f ${BASH_SOURCE[0]})...${NC}"

if [ -z $CLOUD_SHELL ]; then
    err 'Please run this script in Cloud Shell.'
    return 1
fi

if [ "${BASH_SOURCE[0]}" == "$0" ]; then
    err 'Script is not sourced. Please source it.'
    err 'Example: BK_REPO=fhirschmann/bootkon . bk'
    exit 1
fi

if [ -z "$1" ]; then
    if [ -z $BK_REPO ]; then
        err 'Variable BK_REPO is not set. Please set it to a GitHub username and repository'
        err 'Example: BK_REPO=fhirschmann/bootkon . bk'
        return 1
    fi
else
    export BK_REPO=$1
    echo -e "Setting BK_REPO to $BK_REPO based on first argument to this script."
fi

export BK_GITHUB_USERNAME=$(echo $BK_REPO | cut -d/ -f1) # first part of fhirschmann/bootkon
export BK_GITHUB_REPOSITORY=$(echo $BK_REPO | cut -d/ -f2) # second part of fhirschmann/bootkon
export BK_REPO_URL="https://github.com/${BK_REPO}.git"
export BK_TUTORIAL="${BK_TUTORIAL:-docs/TUTORIAL.md}" # defaults to .TUTORIAL.md; can be overwritten
export BK_DIR=~/${BK_GITHUB_REPOSITORY}
export BK_INIT_SCRIPT=~/${BK_GITHUB_REPOSITORY}/bk
export BK_INITIALIZED=1

cd ~/

pip install --quiet jinja2 nbformat nbconvert

if ! command -v git &> /dev/null; then
    sudo apt update
    sudo apt install -y git
fi

if [ -d $BK_GITHUB_REPOSITORY ]; then
    echo -e "${GREEN}Not cloning $BK_REPO_URL because folder ~/$BK_GITHUB_REPOSITORY already exists.${NC}"
else
    echo -e "Cloning $BK_REPO_URL into $BK_GITHUB_REPOSITORY..."
    git clone https://github.com/${BK_REPO}.git
fi

cd $BK_GITHUB_REPOSITORY

NEW_PATH=~/${BK_GITHUB_REPOSITORY}/.scripts

# Check if the new path is already in the PATH
if [[ ":$PATH:" != *":$NEW_PATH:"* ]]; then
echo -e "${MAGENTA}Adding $NEW_PATH to your PATH${NC}"
    export PATH=${NEW_PATH}:$PATH
else
    echo -e "${GREEN}Your PATH already contains $NEW_PATH. Not adding it again.${NC}"
fi
unset NEW_PATH

echo -e "Sourcing $(readlink -f vars.sh)"
source vars.sh

if [ -f vars.local.sh ]; then
    echo -e "Sourcing $(readlink -f vars.local.sh)"
    source vars.local.sh
fi

echo -e "Variables from vars.sh: PROJECT_ID=${YELLOW}$PROJECT_ID${NC} GCP_USERNAME=${YELLOW}$GCP_USERNAME${NC} REGION=${YELLOW}$REGION${NC}"


if [ -z $PROJECT_ID ]; then
    echo -e "The variable PROJECT_ID is empty. Not setting the default Google Cloud project."
else
    gcloud projects get-iam-policy $PROJECT_ID --quiet 2>>/dev/null 1>>/dev/null
    if [ $? -ne 0 ]; then
        echo -en "${RED}ERROR: Unable to get iam policy for project $PROJECT_ID. "
        echo -e "Are you sure you set your PROJECT_ID in vars.sh correctly?${NC}"
        return 1
    fi

    gcloud config set project $PROJECT_ID --quiet 2>>/dev/null

    export PROJECT_NUMBER=$(gcloud projects describe "$PROJECT_ID" --format="value(projectNumber)")
    echo -e "Project for gcloud CLI has been set: PROJECT_ID=${YELLOW}${PROJECT_ID}${NC} PROJECT_NUMBER=${YELLOW}${PROJECT_NUMBER}${NC}."
fi

## Set or update $BK_REPO in ~/.bashrc
line="export BK_REPO=${BK_REPO}"
if grep -q '^export BK_REPO=' ~/.bashrc; then
    # If the line exists but differs, update it
    if ! grep -Fxq "$line" ~/.bashrc; then
        sed -i "s|^export BK_REPO=.*|$line|" ~/.bashrc
        echo "Updated the existing BK_REPO line in ~/.bashrc."
    fi
else
    echo "Adding BK_REPO to .bashrc"
    echo "$line" >> ~/.bashrc
fi

## Set or update $BK_INIT_SCRIPT in ~/.bashrc
line="export BK_INIT_SCRIPT=~/${BK_GITHUB_REPOSITORY}/.scripts/bk"
if grep -q '^export BK_INIT_SCRIPT=' ~/.bashrc; then
    # If the line exists but differs, update it
    if ! grep -Fxq "$line" ~/.bashrc; then
        sed -i "s|^export BK_INIT_SCRIPT=.*|$line|" ~/.bashrc
        echo "Updated the existing BK_INIT_SCRIPT line in ~/.bashrc."
    fi
else
    echo "$line" >> ~/.bashrc
fi

## Load $BK_INIT_SCRIPT in ~/.bashrc
line='if [ -f ${BK_INIT_SCRIPT} ]; then source ${BK_INIT_SCRIPT}; fi'
grep -qxF "$line" ~/.bashrc || echo "$line" >> ~/.bashrc

unset line

echo

cat << "EOF"
         __                 --------------------------------------------------------
 _(\    |@@|                |                                                      |
(__/\__ \--/ __             |          Welcome to the Data & AI Bootkon!           |
   \___|----|  |   __       |                                                      |
       \ }{ /\ )_ / _\      --------------------------------------------------------
       /\__/\ \__O (__
      (--/\--)    \__/
      _)(  )(_
     `---''---`
EOF
echo

if [ "$(basename ${BASH_SOURCE[0]})" != "bk" ]; then
    # This script is run the first time from GitHub
    bk-start
fi  