#!/bin/bash
# Deletes resources created during the labs

case "$1" in
    "all")
    $0 vertex
    ;;
    "vertex")
    echo "Undeploying all models from Vertex AI endpoints with 'bootkon' in their name"

    gcloud ai endpoints list --region=$REGION --format="value(name)" --filter="display_name~bootkon" \
    | while read endpoint; do
        deployed_model_id=$(gcloud ai endpoints describe "$endpoint" --region=$REGION --format="value(deployedModels.id)")
        if [[ -n "$deployed_model_id" ]]; then
            echo "Undeploying model ID $deployed_model_id from endpoint $endpoint"
            gcloud ai endpoints undeploy-model "$endpoint" --deployed-model-id="$deployed_model_id" --region=$REGION --quiet
        fi
    done

    echo "Deleting all Vertex AI models with 'bootkon' in their name"
    gcloud ai models list --format="value(name)" --filter="display_name~bootkon" --region $REGION \
        | xargs -I {} gcloud ai models delete {} --region=$REGION --quiet

    echo "Deleting all Vertex AI endpoints with 'bootkon' in their name"
    gcloud ai endpoints list --format="value(name)" --filter="display_name~bootkon" --region=$REGION \
        | xargs -I {} gcloud ai endpoints delete {} --region=$REGION --quiet

    ;;
    *)
    echo "Usage: $0 <all|vertex>"
esac