#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}Variables:${NC}"
echo -e "BK_GITHUB_USERNAME: ${GREEN}$BK_GITHUB_USERNAME${NC}"
echo -e "BK_GITHUB_REPOSITORY: ${GREEN}$BK_GITHUB_REPOSITORY${NC}"
echo -e "BK_REPO_URL: ${GREEN}$BK_REPO_URL${NC}"
echo -e "BK_TUTORIAL: ${GREEN}$BK_TUTORIAL${NC}"
echo -e "BK_DIR: ${GREEN}$BK_DIR${NC}"
echo -e "BK_INIT_SCRIPT: ${GREEN}$BK_INIT_SCRIPT${NC}"
echo -e "BK_INITIALIZED: ${GREEN}$BK_INITIALIZED${NC}"
echo

echo -e "${CYAN}Info:${NC}"

if [ ! -d "data" ]; then
    echo -e "data: ${RED}does not exist${NC}"
else
    echo -e "data: ${GREEN}exists${NC}"
    du -sh data
fi

echo -e "git origin: ${GREEN}$(git config --get remote.origin.url)${NC}"