#!/bin/bash

# Install Git and Git LFS
if ! $(git lfs 1>>/dev/null 2>>/dev/null); then
    sudo apt-get update
    sudo apt-get install -y git git-lfs
fi

# Retrieve data files
if [ ! -d "data" ]; then
    git clone https://github.com/fhirschmann/bootkon-data.git data
    cd data && git lfs pull
    rm -rf .git .github .gitattributes
else
    echo "Directory 'data' already exists. Not downloading data again"
fi