#!/bin/bash
MEMORY="${BK_DIR}/.tutorial.memory"
RENDERED=/tmp/bootkon.md

FILE=$1

if [[ -z "${FILE}" ]]; then
    if [[ -f "${MEMORY}" ]]; then
        FILE=$(cat $MEMORY)
        echo "No tutorial specified. Reloading last opened file ${FILE}"
    fi
fi

echo "$FILE" > $MEMORY

bk-render-jinja2 $FILE $RENDERED
cloudshell launch-tutorial $RENDERED
cloudshell launch-tutorial $RENDERED
